# Generated by Django 2.1 on 2019-10-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bknNumber', models.CharField(blank=True, max_length=20, verbose_name='物件番号')),
                ('bknName', models.CharField(blank=True, max_length=60, verbose_name='建物名')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格')),
                ('priceTsubo', models.IntegerField(blank=True, null=True, verbose_name='坪単価')),
                ('priceSquare', models.IntegerField(blank=True, null=True, verbose_name='㎡単価')),
                ('planType', models.CharField(blank=True, max_length=10, verbose_name='間取タイプ＋間取部屋数')),
                ('planRoom', models.CharField(blank=True, max_length=30, verbose_name='間取りその他（1）')),
                ('address1', models.CharField(blank=True, max_length=40, verbose_name='都道府県名+所在地名1')),
                ('address2', models.CharField(blank=True, max_length=30, verbose_name='所在地名2')),
                ('railwayLine', models.CharField(blank=True, max_length=20, verbose_name='沿線略称（1）')),
                ('station1', models.CharField(blank=True, max_length=20, verbose_name='駅名（1）')),
                ('walkMin1', models.IntegerField(blank=True, null=True, verbose_name='徒歩（分）1（1）')),
                ('walkMet1', models.IntegerField(blank=True, null=True, verbose_name='徒歩（m）2（1）')),
                ('station2', models.CharField(blank=True, max_length=30, verbose_name='その他交通手段')),
                ('walkMin2', models.IntegerField(blank=True, null=True, verbose_name='交通（分）1')),
                ('walkMet2', models.IntegerField(blank=True, null=True, verbose_name='交通（m）2')),
                ('environment', models.CharField(blank=True, max_length=200, verbose_name='周辺環境1（フリー）')),
                ('environmentMet', models.IntegerField(blank=True, null=True, verbose_name='距離1')),
                ('environmentMin', models.IntegerField(blank=True, null=True, verbose_name='時間1')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='現況')),
                ('bknTrade', models.CharField(blank=True, max_length=20, verbose_name='物件種別')),
                ('bknType', models.CharField(blank=True, max_length=20, verbose_name='物件番号')),
                ('exclusiveArea', models.FloatField(blank=True, null=True, verbose_name='専有面積')),
                ('balArea', models.FloatField(blank=True, null=True, verbose_name='バルコニー（テラス）面積')),
                ('associationFlag', models.CharField(blank=True, max_length=10, verbose_name='管理組合有無')),
                ('associationType', models.CharField(blank=True, max_length=20, verbose_name='管理形態')),
                ('administrative', models.IntegerField(blank=True, null=True, verbose_name='管理費')),
                ('repairReserve', models.IntegerField(blank=True, null=True, verbose_name='修繕積立金')),
                ('structure', models.CharField(blank=True, max_length=20, verbose_name='建物構造')),
                ('stairs', models.CharField(blank=True, max_length=10, verbose_name='所在階/地上階層')),
                ('balDirection', models.CharField(blank=True, max_length=10, verbose_name='バルコニー方向（1）')),
                ('constructionDate', models.CharField(blank=True, max_length=10, verbose_name='築年月（西暦）')),
                ('extensionDate1', models.CharField(blank=True, max_length=10, verbose_name='増改築年月1')),
                ('extensionHistory1', models.CharField(blank=True, max_length=200, verbose_name='増改築履歴1')),
                ('extensionDate2', models.CharField(blank=True, max_length=10, verbose_name='増改築年月2')),
                ('extensionHistory2', models.CharField(blank=True, max_length=200, verbose_name='増改築履歴2')),
                ('extensionDate3', models.CharField(blank=True, max_length=10, verbose_name='増改築年月3')),
                ('extensionHistory3', models.CharField(blank=True, max_length=200, verbose_name='増改築履歴3')),
            ],
        ),
        migrations.CreateModel(
            name='SimplePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
