# Generated by Django 2.1 on 2019-10-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toppage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pictureFlag',
            field=models.IntegerField(blank=True, null=True, verbose_name='写真有無'),
        ),
    ]
