# Generated by Django 2.1 on 2019-10-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toppage', '0005_auto_20191013_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='soldout',
            field=models.CharField(blank=True, max_length=2, verbose_name='契約済み'),
        ),
    ]
